"""
output.py

Structured output parser for the Explainable AI Maturity Assessment System.

This module provides:
- Pydantic models for structured LLM output
- validation rules for consistent response formatting
- parsing utilities for raw LLM responses
- prompt instructions that enforce JSON-only output

It is designed for scenarios where the LLM should return advisory-style
structured responses that can be:
- validated automatically
- stored in a database
- rendered in APIs or dashboards
- converted into readable summaries

This module is especially useful for a future advisory layer or V2 workflow.
"""

from __future__ import annotations

import json
import re
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator


# =============================================================================
# Enums
# =============================================================================

class RiskLevel(str, Enum):
    """
    Allowed risk levels for structured advisory output.
    """
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class Dimension(str, Enum):
    """
    Allowed maturity dimensions.
    """
    T = "T"
    P = "P"
    R = "R"
    A = "A"


# =============================================================================
# Sub-models
# =============================================================================

class Priority(BaseModel):
    """
    One prioritized recommendation item.
    """
    rank: int = Field(..., ge=1, le=3, description="Priority rank from 1 to 3")
    dimension: Dimension = Field(..., description="Affected maturity dimension")
    action: str = Field(..., min_length=5, description="Concrete action to take")
    rationale: str = Field(..., min_length=5, description="Reason for the action")
    timeframe: Optional[str] = Field(None, description="Optional timeframe, e.g. '4-6 weeks'")


class LeverAnalysis(BaseModel):
    """
    The dimension with the greatest leverage for improvement.
    """
    dimension: Dimension = Field(..., description="Highest-leverage dimension")
    explanation: str = Field(..., description="Why this dimension matters most")


class RiskAssessment(BaseModel):
    """
    Risk outlook if no action is taken.
    """
    level: RiskLevel = Field(..., description="Risk level: low / medium / high")
    consequence: str = Field(..., description="Specific consequence of inaction")


class NextStep(BaseModel):
    """
    One immediate action item.
    """
    action: str = Field(..., description="Immediate next action")
    owner: Optional[str] = Field(None, description="Responsible role or owner")
    by_when: Optional[str] = Field(None, description="Target timing")


# =============================================================================
# Main output model
# =============================================================================

class AdvisorOutput(BaseModel):
    """
    Fully structured advisory output generated by the LLM.

    This object is intended for:
    - API responses
    - dashboard rendering
    - database persistence
    - internal logging
    """
    summary: str = Field(..., description="2-3 sentence system assessment")
    top_priorities: List[Priority] = Field(..., min_length=1, max_length=3)
    lever: LeverAnalysis
    risk: RiskAssessment
    next_step: NextStep
    rag_references: List[str] = Field(default_factory=list, description="Referenced knowledge sources")

    @field_validator("top_priorities")
    @classmethod
    def priorities_must_be_ranked(cls, value: List[Priority]) -> List[Priority]:
        """
        Ensure priorities are ranked sequentially from 1 upward.
        """
        ranks = [p.rank for p in value]
        if sorted(ranks) != list(range(1, len(ranks) + 1)):
            raise ValueError("Top priorities must be ranked sequentially starting at 1.")
        return sorted(value, key=lambda p: p.rank)

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert the validated output to a plain dictionary.
        """
        return self.model_dump()

    def summary_text(self) -> str:
        """
        Convert the structured output into a readable multiline text summary.
        Useful for logs, CLI previews, or UI rendering.
        """
        lines = [
            "── Overall assessment ───────────────────────────────────────",
            self.summary,
            "\n── Top priorities ───────────────────────────────────────────",
        ]

        for priority in self.top_priorities:
            tf = f" ({priority.timeframe})" if priority.timeframe else ""
            lines.append(f"  {priority.rank}. [{priority.dimension.value}] {priority.action}{tf}")
            lines.append(f"     → {priority.rationale}")

        lines += [
            "\n── Highest leverage ─────────────────────────────────────────",
            f"  {self.lever.dimension.value}: {self.lever.explanation}",
            "\n── Risk outlook ─────────────────────────────────────────────",
            f"  Level: {self.risk.level.value.upper()}",
            f"  {self.risk.consequence}",
            "\n── Next step ────────────────────────────────────────────────",
            f"  {self.next_step.action}",
        ]

        if self.next_step.owner:
            lines.append(f"  Owner: {self.next_step.owner}")
        if self.next_step.by_when:
            lines.append(f"  By: {self.next_step.by_when}")

        if self.rag_references:
            lines.append("\n── References ───────────────────────────────────────────────")
            for ref in self.rag_references:
                lines.append(f"  - {ref}")

        return "\n".join(lines)


# =============================================================================
# Prompt schema and instruction
# =============================================================================

OUTPUT_SCHEMA = """
{
  "summary": "2-3 sentence system assessment",
  "top_priorities": [
    {
      "rank": 1,
      "dimension": "P",
      "action": "Concrete action",
      "rationale": "Reasoning",
      "timeframe": "4-6 weeks"
    }
  ],
  "lever": {
    "dimension": "P",
    "explanation": "Why this dimension has the highest leverage"
  },
  "risk": {
    "level": "high",
    "consequence": "What happens if no action is taken"
  },
  "next_step": {
    "action": "Immediate action",
    "owner": "e.g. Operations Lead",
    "by_when": "e.g. this week"
  },
  "rag_references": ["Source 1", "Source 2"]
}
"""

OUTPUT_INSTRUCTION = f"""
Respond only with one valid JSON object.
Do not add explanations before or after the JSON.
Do not wrap the JSON in Markdown code fences.

Follow this exact schema:

{OUTPUT_SCHEMA}

Allowed values:
- dimension: "T", "P", "R", or "A"
- risk.level: "low", "medium", or "high"
- top_priorities: between 1 and 3 items, ranked sequentially starting at 1
"""


# =============================================================================
# Parsing utilities
# =============================================================================

def parse_llm_output(raw: str) -> AdvisorOutput:
    """
    Parse raw LLM text into a validated AdvisorOutput object.

    Parsing flow:
    1. extract JSON from raw text
    2. decode JSON
    3. validate with Pydantic
    4. raise OutputParseError on failure

    Args:
        raw: Raw text returned by the LLM.

    Returns:
        Validated AdvisorOutput object.
    """
    cleaned = _extract_json(raw)

    try:
        data = json.loads(cleaned)
    except json.JSONDecodeError as exc:
        raise OutputParseError(
            f"Could not parse JSON: {exc}",
            raw_text=raw,
        ) from exc

    try:
        return AdvisorOutput(**data)
    except Exception as exc:
        raise OutputParseError(
            f"Validation failed: {exc}",
            raw_text=raw,
        ) from exc


def _extract_json(text: str) -> str:
    """
    Extract a JSON object from raw LLM output.

    Supports:
    - plain JSON text
    - JSON wrapped in ```json ... ```
    - responses with extra surrounding text

    Args:
        text: Raw LLM response text.

    Returns:
        Extracted JSON string if found, otherwise the stripped raw text.
    """
    code_block_match = re.search(r"```(?:json)?\s*([\s\S]+?)\s*```", text)
    if code_block_match:
        return code_block_match.group(1).strip()

    start = text.find("{")
    end = text.rfind("}")

    if start != -1 and end != -1 and end > start:
        return text[start:end + 1].strip()

    return text.strip()


# =============================================================================
# Error type
# =============================================================================

class OutputParseError(Exception):
    """
    Raised when raw LLM output cannot be parsed or validated.
    """

    def __init__(self, message: str, raw_text: str = "") -> None:
        super().__init__(message)
        self.raw_text = raw_text


# =============================================================================
# Prompt integration helper
# =============================================================================

def inject_output_instruction(system_prompt: str) -> str:
    """
    Append the structured-output instruction to an existing system prompt.

    Args:
        system_prompt: Base system prompt string.

    Returns:
        Extended system prompt including JSON output constraints.
    """
    return system_prompt.rstrip() + "\n\n" + OUTPUT_INSTRUCTION.strip()


def build_executive_summary(result):
    weakest = result["weaknesses"][0] if result["weaknesses"] else "no major constraint"
    strongest = result["strengths"][0] if result["strengths"] else "no strong leverage"

    readiness = result["overall_readiness"]

    return f"""
The current system shows an overall readiness of {readiness:.1f}.

The primary constraint lies in {weakest}, limiting reliable execution and scalability.
At the same time, {strongest} represents a key strength that can be leveraged to accelerate improvements.

Focusing on resolving the constraint while utilizing existing strengths will enable faster and more sustainable system development.
"""